services:
  sipetra-app:
    container_name: sipetra-app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=:80
      - DB_CONNECTION=mysql
      - DB_HOST=sipetra-db
      - DB_PORT=3306
      - DB_DATABASE=sipetra_db
      - DB_USERNAME=sipetra_user
      - DB_PASSWORD=sipetra_pass
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - sipetra-db
    networks:
      - sipetra-network

  sipetra-db:
    image: mysql:8.0
    container_name: sipetra-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sipetra_db
      MYSQL_USER: sipetra_user
      MYSQL_PASSWORD: sipetra_pass
    volumes:
      - sipetra_db_data:/var/lib/mysql
    networks:
      - sipetra-network

networks:
  sipetra-network:
    driver: bridge

volumes:
  sipetra_db_data:
