services:
  sipetra-app:
    container_name: sipetra-app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=:80
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - .docker/php/conf.d/extra.ini:/usr/local/etc/php/conf.d/extra.ini:ro
    networks:
      - default
      - mysql-stack_mysql_network

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
