services:
  sipetra-app:
    container_name: sipetra-app
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_NAME=:80
      # Pastikan DB_HOST sesuai dengan nama container MySQL di network mysql-stack
      # - DB_CONNECTION=mysql
      # - DB_HOST=mysql
      # - DB_PORT=3306
      # - DB_DATABASE=sipetra
      # - DB_USERNAME=root
      # - DB_PASSWORD=
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - default
      - mysql-stack_mysql_network

networks:
  default: {}
  mysql-stack_mysql_network:
    external: true
